In [2]:
import pandas as pd
import matplotlib as mb

In [5]:
df_sales = pd.read_csv('/workspaces/Finance_Pandas_Analysis/Data File/sales.csv')

In [11]:
df_sales.head()

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32
1,2023-01-02,Toys,569.48,3.60,Premium,6807.56,16
2,2023-01-03,Home Decor,699.68,3.56,Premium,3793.91,27
3,2023-01-04,Toys,923.27,0.61,Premium,9422.75,29
4,2023-01-05,Toys,710.17,47.83,Premium,1756.83,17

In [7]:
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATE              100 non-null    str
 1   PRODUCT_CATEGORY  100 non-null    str
 2   PRICE             100 non-null    float64
 3   DISCOUNT          100 non-null    float64
 4   CUSTOMER_SEGMENT  100 non-null    str
 5   MARKETING_SPEND   100 non-null    float64
 6   UNITS_SOLD        100 non-null    int64
dtypes: float64(3), int64(1), str(3)
memory usage: 5.6 KB

In [9]:
df_sales.describe()

            PRICE    DISCOUNT  MARKETING_SPEND  UNITS_SOLD
count  100.000000  100.000000       100.000000  100.000000
mean   479.268600   26.024000      5008.742400   29.440000
std    289.049567   14.744561      2979.045902    6.601683
min     14.590000    0.470000       289.530000   13.000000
25%    213.050000   12.255000      2190.112500   25.000000
50%    457.810000   28.685000      4916.520000   30.000000
75%    712.330000   38.280000      7860.615000   34.000000
max    996.910000   49.590000      9972.660000   49.000000

100