In [86]:
import pandas as pd
import matplotlib.pyplot as plt

In [87]:
df_sales = pd.read_csv('/workspaces/Finance_Pandas_Analysis/Data File/sales.csv')

In [88]:
df_sales.head()

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32
1,2023-01-02,Toys,569.48,3.60,Premium,6807.56,16
2,2023-01-03,Home Decor,699.68,3.56,Premium,3793.91,27
3,2023-01-04,Toys,923.27,0.61,Premium,9422.75,29
4,2023-01-05,Toys,710.17,47.83,Premium,1756.83,17

In [89]:
df_sales['DATE'] = pd.to_datetime(df_sales['DATE'])

In [90]:
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATE              1000 non-null   datetime64[us]
 1   PRODUCT_CATEGORY  1000 non-null   str
 2   PRICE             1000 non-null   float64
 3   DISCOUNT          1000 non-null   float64
 4   CUSTOMER_SEGMENT  1000 non-null   str
 5   MARKETING_SPEND   1000 non-null   float64
 6   UNITS_SOLD        1000 non-null   int64
dtypes: datetime64[us](1), float64(3), int64(1), str(2)
memory usage: 54.8 KB

In [91]:
round(df_sales[['PRICE', 'DISCOUNT', 'MARKETING_SPEND', 'UNITS_SOLD']].describe(), 2)

         PRICE  DISCOUNT  MARKETING_SPEND  UNITS_SOLD
count  1000.00   1000.00          1000.00     1000.00
mean    505.24     24.92          4912.83       29.63
std     289.79     14.44          2840.60        7.27
min      14.59      0.01           100.30        5.00
25%     243.34     13.00          2413.02       24.00
50%     509.31     24.96          4837.25       30.00
75%     747.59     37.56          7319.68       34.00
max     999.42     49.92          9995.62       57.00

In [92]:
df_sales.shape

(1000, 7)

In [93]:
df_sales_new = df_sales.dropna(how='any')

In [94]:
df_sales_new.drop_duplicates()

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32
1,2023-01-02,Toys,569.48,3.60,Premium,6807.56,16
2,2023-01-03,Home Decor,699.68,3.56,Premium,3793.91,27
3,2023-01-04,Toys,923.27,0.61,Premium,9422.75,29
4,2023-01-05,Toys,710.17,47.83,Premium,1756.83,17
...,...,...,...,...,...,...,...
995,2025-09-22,Fashion,740.06,49.06,Regular,1890.83,34
996,2025-09-23,Electronics,517.10,28.48,Premium,8011.66,21
997,2025-09-24,Electronics,683.43,12.98,Occasional,3408.51,19
998,2025-09-25,Sports,51.26,21.85,Occasional,7335.62,26
999,2025-09-26,Home Decor,93.94,29.68,Regular,4258.11,39

In [95]:
df_sales_new.duplicated().sum()

np.int64(0)

In [96]:
df_sales_new['PRICE'].agg(['mean', 'std', 'max', 'median'])

mean      505.241920
std       289.791248
max       999.420000
median    509.310000
Name: PRICE, dtype: float64

In [ ]:
#df_sales_new[df_sales_new[]].sort()