In [86]:
import pandas as pd
import matplotlib.pyplot as plt

In [87]:
df_sales = pd.read_csv('/workspaces/Finance_Pandas_Analysis/Data File/sales.csv')

In [88]:
df_sales.head()

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32
1,2023-01-02,Toys,569.48,3.60,Premium,6807.56,16
2,2023-01-03,Home Decor,699.68,3.56,Premium,3793.91,27
3,2023-01-04,Toys,923.27,0.61,Premium,9422.75,29
4,2023-01-05,Toys,710.17,47.83,Premium,1756.83,17

In [89]:
df_sales['DATE'] = pd.to_datetime(df_sales['DATE'])

In [90]:
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATE              1000 non-null   datetime64[us]
 1   PRODUCT_CATEGORY  1000 non-null   str
 2   PRICE             1000 non-null   float64
 3   DISCOUNT          1000 non-null   float64
 4   CUSTOMER_SEGMENT  1000 non-null   str
 5   MARKETING_SPEND   1000 non-null   float64
 6   UNITS_SOLD        1000 non-null   int64
dtypes: datetime64[us](1), float64(3), int64(1), str(2)
memory usage: 54.8 KB

In [91]:
round(df_sales[['PRICE', 'DISCOUNT', 'MARKETING_SPEND', 'UNITS_SOLD']].describe(), 2)

         PRICE  DISCOUNT  MARKETING_SPEND  UNITS_SOLD
count  1000.00   1000.00          1000.00     1000.00
mean    505.24     24.92          4912.83       29.63
std     289.79     14.44          2840.60        7.27
min      14.59      0.01           100.30        5.00
25%     243.34     13.00          2413.02       24.00
50%     509.31     24.96          4837.25       30.00
75%     747.59     37.56          7319.68       34.00
max     999.42     49.92          9995.62       57.00

In [92]:
df_sales.shape

(1000, 7)

In [93]:
df_sales_new = df_sales.dropna(how='any')

In [94]:
df_sales_new.drop_duplicates()

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
0,2023-01-01,Sports,932.80,35.82,Occasional,6780.38,32
1,2023-01-02,Toys,569.48,3.60,Premium,6807.56,16
2,2023-01-03,Home Decor,699.68,3.56,Premium,3793.91,27
3,2023-01-04,Toys,923.27,0.61,Premium,9422.75,29
4,2023-01-05,Toys,710.17,47.83,Premium,1756.83,17
...,...,...,...,...,...,...,...
995,2025-09-22,Fashion,740.06,49.06,Regular,1890.83,34
996,2025-09-23,Electronics,517.10,28.48,Premium,8011.66,21
997,2025-09-24,Electronics,683.43,12.98,Occasional,3408.51,19
998,2025-09-25,Sports,51.26,21.85,Occasional,7335.62,26
999,2025-09-26,Home Decor,93.94,29.68,Regular,4258.11,39

In [95]:
df_sales_new.duplicated().sum()

np.int64(0)

In [96]:
df_sales_new['PRICE'].agg(['mean', 'std', 'max', 'median'])

mean      505.241920
std       289.791248
max       999.420000
median    509.310000
Name: PRICE, dtype: float64

In [99]:
df_sales_new['DISCOUNT'].agg(['mean', 'std', 'max', 'median'])

mean      24.919750
std       14.439951
max       49.920000
median    24.965000
Name: DISCOUNT, dtype: float64

In [101]:
df_sales_new['CUSTOMER_SEGMENT'].value_counts()

CUSTOMER_SEGMENT
Regular       345
Occasional    339
Premium       316
Name: count, dtype: int64

In [104]:
df_sales_new.sort_values(by='PRICE', ascending=False).head(10)

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
668,2024-10-30,Fashion,999.42,31.03,Occasional,7175.72,25
258,2023-09-16,Fashion,997.95,42.50,Regular,9637.27,35
413,2024-02-18,Sports,997.15,45.54,Occasional,1148.16,21
51,2023-02-21,Sports,996.91,9.87,Regular,9972.66,25
931,2025-07-20,Electronics,996.73,11.41,Regular,5781.27,24
537,2024-06-21,Home Decor,996.37,34.33,Premium,3440.80,30
308,2023-11-05,Toys,994.96,39.66,Regular,8326.40,39
919,2025-07-08,Sports,994.92,14.99,Regular,2102.71,38
820,2025-03-31,Electronics,994.20,18.01,Regular,9550.20,28
842,2025-04-22,Electronics,992.56,47.54,Regular,9089.38,40

In [106]:
df_sales_new.sort_values(by='DISCOUNT', ascending=False).head(10)

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
158,2023-06-08,Electronics,424.58,49.92,Regular,9702.27,27
733,2025-01-03,Fashion,543.77,49.89,Occasional,1418.78,15
116,2023-04-27,Fashion,627.91,49.82,Regular,6705.40,28
447,2024-03-23,Electronics,846.34,49.77,Occasional,5448.94,36
993,2025-09-20,Fashion,523.22,49.74,Premium,4155.76,35
664,2024-10-26,Home Decor,399.93,49.69,Occasional,3475.49,30
518,2024-06-02,Toys,457.80,49.64,Regular,4037.08,22
93,2023-04-04,Home Decor,250.74,49.59,Regular,8660.12,29
940,2025-07-29,Fashion,455.29,49.57,Occasional,5458.57,28
612,2024-09-04,Toys,589.50,49.40,Regular,2604.96,24

In [107]:
df_sales_new.sort_values(by='MARKETING_SPEND', ascending=False).head(10)

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
198,2023-07-18,Toys,367.36,37.57,Occasional,9995.62,38
805,2025-03-16,Fashion,330.14,2.72,Regular,9977.72,34
51,2023-02-21,Sports,996.91,9.87,Regular,9972.66,25
724,2024-12-25,Electronics,69.66,34.63,Regular,9956.13,22
582,2024-08-05,Electronics,365.64,22.32,Occasional,9926.56,22
987,2025-09-14,Sports,640.83,39.66,Regular,9925.89,34
608,2024-08-31,Fashion,667.17,33.86,Premium,9920.43,32
473,2024-04-18,Toys,298.75,25.62,Premium,9904.29,26
263,2023-09-21,Electronics,631.23,27.27,Occasional,9902.08,28
953,2025-08-11,Toys,145.74,31.80,Premium,9896.10,15

In [111]:
df_sales_new.sort_values(by='UNITS_SOLD', ascending=False).head(10)

,DATE,PRODUCT_CATEGORY,PRICE,DISCOUNT,CUSTOMER_SEGMENT,MARKETING_SPEND,UNITS_SOLD
641,2024-10-03,Toys,707.63,17.02,Occasional,4837.43,57
522,2024-06-06,Sports,90.81,21.09,Occasional,7123.44,52
138,2023-05-19,Fashion,179.96,33.82,Occasional,2044.55,50
544,2024-06-28,Electronics,265.11,37.56,Occasional,4476.86,50
53,2023-02-23,Toys,599.43,32.29,Regular,8983.92,49
628,2024-09-20,Sports,986.76,14.46,Occasional,2340.10,48
521,2024-06-05,Electronics,734.27,19.73,Premium,2824.87,47
720,2024-12-21,Home Decor,651.00,0.96,Regular,9874.63,47
136,2023-05-17,Sports,984.56,28.03,Regular,7648.22,47
661,2024-10-23,Fashion,679.75,31.31,Premium,787.00,47

In [116]:
df_sales_new.groupby('PRODUCT_CATEGORY')['UNITS_SOLD'].sum()

PRODUCT_CATEGORY
Electronics    6210
Fashion        5650
Home Decor     5643
Sports         6125
Toys           6003
Name: UNITS_SOLD, dtype: int64

In [118]:
df_sales_new.groupby('CUSTOMER_SEGMENT')['UNITS_SOLD'].sum()

CUSTOMER_SEGMENT
Occasional     9842
Premium        9567
Regular       10222
Name: UNITS_SOLD, dtype: int64